// <auto-generated />
using System;
using AgendaMedica.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendaMedica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250228175049_migracaoinicial")]
    partial class migracaoinicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgendaMedica.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicalSpecialtyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalSpecialtyId");

                    b.ToTable("Doctor", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Models.MedicalConsultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ConsultationDate")
                        .HasColumnType("date");

                    b.Property<int>("ConsultationTime")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalConsultationStatusId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalSpecialtyId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MedicalConsultationStatusId");

                    b.HasIndex("MedicalSpecialtyId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalConsultation", (string)null);
                });

            modelBuilder.Entity("AgendaMedica.Models.MedicalConsultationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StatusConsulta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Agendada"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Cancelada"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Realizada"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Remarcada"
                        });
                });

            modelBuilder.Entity("AgendaMedica.Models.MedicalSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MedicalSpecialty", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Especialidade médica que se ocupa do diagnóstico e tratamento de doenças que acometem o coração e o sistema circulatório.",
                            Name = "Cardiologia"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Especialidade médica que se ocupa do diagnóstico e tratamento clínico-cirúrgico das doenças da pele.",
                            Name = "Dermatologia"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Especialidade médica que estuda as ordens do sistema endócrino e suas secreções específicas, chamadas de secreções fisiológicas.",
                            Name = "Endocrinologia"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Especialidade médica que se ocupa do estudo, diagnóstico e tratamento clínico das doenças do aparelho digestivo.",
                            Name = "Gastroenterologia"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Especialidade médica que se ocupa do diagnóstico e tratamento das doenças do sistema reprodutor feminino.",
                            Name = "Ginecologia"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Especialidade médica que se ocupa do diagnóstico e tratamento de doenças que acometem o sistema nervoso.",
                            Name = "Neurologia"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Especialidade médica que se ocupa do diagnóstico e tratamento de doenças oculares.",
                            Name = "Oftalmologia"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Especialidade médica que se ocupa do diagnóstico e tratamento de doenças e deformidades dos ossos, músculos, ligamentos e articulações.",
                            Name = "Ortopedia"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Especialidade médica que se ocupa do diagnóstico e tratamento de doenças do ouvido, nariz e garganta.",
                            Name = "Otorrinolaringologia"
                        });
                });

            modelBuilder.Entity("AgendaMedica.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Patient", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rua 1",
                            Cpf = "12345678901",
                            DateOfBirth = new DateOnly(1990, 1, 1),
                            Name = "Maria",
                            Phone = "11999999999"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Rua 2",
                            Cpf = "12345678902",
                            DateOfBirth = new DateOnly(1991, 2, 2),
                            Name = "João",
                            Phone = "11999999998"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Rua 3",
                            Cpf = "12345678903",
                            DateOfBirth = new DateOnly(1992, 3, 3),
                            Name = "José",
                            Phone = "11999999997"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Rua 4",
                            Cpf = "12345678904",
                            DateOfBirth = new DateOnly(1993, 4, 4),
                            Name = "Ana",
                            Phone = "11999999996"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Rua 5",
                            Cpf = "12345678905",
                            DateOfBirth = new DateOnly(1994, 5, 5),
                            Name = "Pedro",
                            Phone = "11999999995"
                        });
                });

            modelBuilder.Entity("AgendaMedica.Models.Doctor", b =>
                {
                    b.HasOne("AgendaMedica.Models.MedicalSpecialty", "MedicalSpecialty")
                        .WithMany()
                        .HasForeignKey("MedicalSpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalSpecialty");
                });

            modelBuilder.Entity("AgendaMedica.Models.MedicalConsultation", b =>
                {
                    b.HasOne("AgendaMedica.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AgendaMedica.Models.MedicalConsultationStatus", "MedicalConsultationStatus")
                        .WithMany()
                        .HasForeignKey("MedicalConsultationStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AgendaMedica.Models.MedicalSpecialty", "MedicalSpecialty")
                        .WithMany()
                        .HasForeignKey("MedicalSpecialtyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AgendaMedica.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("MedicalConsultationStatus");

                    b.Navigation("MedicalSpecialty");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
